name: demo-service

replicas: 1

container:
  image: example.io/demo-service
  version: v1-build-2568
  port: 3201

resources:
  limitMemory: 128Mi
  requestMemory: 64Mi

secret:
  store: vault-secret
  name: secret-demo-service
  key: secret/staging/config
  refresh: "1m"

scale:
  replicaCount:
    min: 1
    max: 10
  pollingInterval: 10
  cooldownPeriod: 60
  refresh: 2m
  threshold: 40

service:
  name: demo-service.example.svc.cluster.local:3201

prometheus:
  host: http://prometheus-server.monitoring.svc.cluster.local
