apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  refreshInterval: {{ .Values.secret.refresh }}
  secretStoreRef:
    name: {{ .Values.secret.store }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
  data:
  - secretKey: CORE_DATA_MONGODB_DB
    remoteRef:
      key: {{ .Values.secret.key }}
      property: CORE_DATA_MONGODB_DB
  - secretKey: CORE_DATA_MONGODB_URI
    remoteRef:
      key: {{ .Values.secret.key }}
      property: CORE_DATA_MONGODB_URI
  - secretKey: CORE_CACHE_MODE
    remoteRef:
      key: {{ .Values.secret.key }}
      property: CORE_CACHE_MODE
  - secretKey: CORE_CACHE_OPTION_REDIS
    remoteRef:
      key: {{ .Values.secret.key }}
      property: CORE_CACHE_OPTION_REDIS
  - secretKey: CORE_CACHE_OPTION_TTL
    remoteRef:
      key: {{ .Values.secret.key }}
      property: CORE_CACHE_OPTION_TTL
  - secretKey: SERVICE_CONFIGURATION_URL
    remoteRef:
      key: {{ .Values.secret.key }}
      property: SERVICE_CONFIGURATION_URL
  - secretKey: SERVICE_CALL_CENTER_URL
    remoteRef:
      key: {{ .Values.secret.key }}
      property: SERVICE_CALL_CENTER_URL
  - secretKey: TRANSACTION_ENDPOINT_API
    remoteRef:
      key: {{ .Values.secret.key }}
      property: TRANSACTION_ENDPOINT_API
  - secretKey: SERVICE_REPORT_SCHEMA_URL
    remoteRef:
      key: {{ .Values.secret.key }}
      property: SERVICE_REPORT_SCHEMA_URL
